version = 0.1
[default.deploy.parameters]
stack_name = "stack-trivia-app-0613a"
resolve_s3 = true
s3_prefix = "stack-trivia-app-0613a"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
